### ISSUE TITLE
how to make this project work ?

### ISSUE THREAD

**Issue by dinhduynhat** [prosteNoBody/mmtrading#2]
hi.. :v my question on title <3, thanks

**Comment by prosteNoBody** [comment]
Hi, this is actually my school project so it is not meant to be public but you can try make it work by filling out keys.json in server folder, then it should work ;)

**Comment by dinhduynhat** [comment]
i haven't  add key.json yet, but when i start it. it close :< 
![image](https://user-images.githubusercontent.com/20450856/102917066-20819800-44b7-11eb-9a01-95bd1b018cca.png)

**Comment by dinhduynhat** [comment]
btw, your idea project verry good bro:> i luv it

**Comment by dinhduynhat** [comment]
ahhh i got it : node server/server.js :<< tks

**Comment by prosteNoBody** [comment]
if you check package.json you can see that that npm start is for production but there is no production yet xd so use npm run dev instead and thanks but do you even know what this project should do?

**Comment by dinhduynhat** [comment]
long time ago i have idea like this too, but i'm a designer :< i does know much about code :< i think we need contact to have a real project tho

**Comment by prosteNoBody** [comment]
sounds good xd you can check how design look like :P awful...

**Comment by dinhduynhat** [comment]
addfriend me bro : https://www.facebook.com/xsuiix/

**Comment by prosteNoBody** [comment]
I rather use dicsord, if you want you can contact me there "NoBody#0340"

**Comment by dinhduynhat** [comment]
sure
